### ISSUE TITLE
Email images are not working.

### ISSUE THREAD

**Issue by pierre-denissen** [yireo/Yireo_Webp2#11]
Hi,

We have implemented this great extension. However, it seems that the extension breaks the images in the transactional emails.

The images renders like this in Gmail:
```
<td style="width:12%;padding-top:5px;padding-bottom:5px;line-height:1">
     <u></u>
     <u></u>
     <u></u>
     <img alt="my_alt_text" width="70" height="70">
    <u></u>
</td>
```
The src attribute is missing here. It seems like Gmail strips down the entire `<picture>` element.

Is there a way to ignore the email templates?

Looking forward for a great solution.

Kind regards,
Pierre

**Comment by jissereitsma** [comment]
Indeed, the WebP module should not be active when emails are dealt with. There are too many issues with outdated email clients. Unfortunately, there are no solid ways to detect that the Layout is loaded as part of the email procedure. I've now released a new version 0.4.3 that attempts to fix things. It seems that, when email templates are loaded, the list of Layout Handles is empty, so this is now used as a fix. But I'm not sure if this condition (that email templates have no handles) is true in all cases. Cross fingers.

**Comment by jissereitsma** [comment]
https://github.com/yireo/Yireo_Webp2/releases/tag/0.4.3

**Comment by pierre-denissen** [comment]
Hi @jissereitsma ,
Thanks for the update. We're going to update the module. I will give some feedback if it's solved.

Thanks!

**Comment by pdenissen** [comment]
Hi @jissereitsma ,

We have updated the module to version 0.4.3. It seems that the issue still remains. 
The output of the image in the email is:
```
<td class="item-image" style="width: 12%; padding-top: 5px; padding-bottom: 5px; line-height: 1;">
<picture>
    <source data-srcset="https://our-site.com/media/catalog/product/cache/006eb0acba17f336b95845fe38c889f1/2/d/2d65c39666c7e50dd1a2ac382151424157c82d95_as0015930_3_def.webp" type="image/webp">
    <source data-srcset="https://our-site.com/media/catalog/product/cache/006eb0acba17f336b95845fe38c889f1/2/d/2d65c39666c7e50dd1a2ac382151424157c82d95_as0015930_3_def.png" type="image/png">
    <img class="lazyload" data-src="https://our-site.com/media/catalog/product/cache/006eb0acba17f336b95845fe38c889f1/2/d/2d65c39666c7e50dd1a2ac382151424157c82d95_as0015930_3_def.png" alt="our alt text" width="70" height="70">
</picture>
</td>
```
Is there any other solution we can think of?

Thanks in advance.

**Comment by jissereitsma** [comment]
I've tested this out again and do not get the same results as you do. Except for when a specific handle is loaded in the email itself, like `sales_email_order_invoice_items`. While rendering the layout, there seems no other way to see whether a specific block was loaded in an email or not than to match it with specific layout handles. The mentioned handle is now added to a list of handles here: 
https://github.com/yireo/Yireo_Webp2/blob/master/Plugin/ReplaceTags.php#L76 

Make sure to upgrade to 0.4.5 for this. Maybe this release already works for you. Maybe it doesn't. In that case, also see the new FAQ in the bottom here: https://github.com/yireo/Yireo_Webp2/blob/master/FAQ.md

**Comment by sdouma** [comment]
I know emails very well. Using webp is a very very bad idea. Google doesn't even use webp in their emails. I think you should revert the commits. Support isn't there even among modern email clients.

**Comment by pdenissen** [comment]
> I know emails very well. Using webp is a very very bad idea. Google doesn't even use webp in their emails. I think you should revert the commits. Support isn't there even among modern email clients.

That’s where this issue is about. Removing webp images from emails ;-)

**Comment by sdouma** [comment]
> > I know emails very well. Using webp is a very very bad idea. Google doesn't even use webp in their emails. I think you should revert the commits. Support isn't there even among modern email clients.
> 
> That’s where this issue is about. Removing webp images from emails ;-)

sorry I misread

**Comment by jissereitsma** [comment]
I'm closing this issue for now. Feel free to re-open if you think this issue still applies.
